name: Build OurLoop RU AdHoc
run-name: Build OurLoop RU AdHoc (${{ github.ref_name }})

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-adhoc:
    if: github.ref == 'refs/heads/ourloop-ru'
    uses: ./.github/workflows/build_ourloop_ru_adhoc.yml
    secrets: inherit
